name = "ZeroSumGameSolve"
uuid = "acbac2c1-af1f-4c5c-8072-533d2c216f7a"
authors = ["Kushagra Gupta, Cade Armstrong, Dong Ho Lee, Jacob Levy, Fernando Palafox Escobedo, David Fridovich-Keil"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
